version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    image: go_crud_postgresql
    ports:
      - "8081:8081"
    restart: always # Reinicio del microservicio en caso de fallo
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: prograred
    restart: always # Reinicio del microservicio en caso de fallo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
